spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: xxx
    password: xxx

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

application:
  security:
    jwt:
      secret-key: "xxxx" # len >= 64
      expiration: 60000 #ms
      refresh-expiration: 604800000